version: '3'
services:
  mysql:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      #MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'analisecredito'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
    # expose:
    #   - '3306'
    ports:
      - "3309:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"
    networks:
      - api

  pgadmin4:
    image: dpage/pgadmin4:4.10
    container_name: "pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "8082:80"
    networks:
      - api

networks:
  api:
    driver: bridge
